version: "3.9"

services:
  controlserver:
    build: ./control_server
    container_name: control_server
    networks:
      simnet:
        ipv4_address: 10.10.0.1
    ports:
      - "9000:9000"   # Expose control port for external client connections

  servernode:
    build: ./server_node
    container_name: server_node
    networks:
      simnet:
        ipv4_address: 10.10.0.2
    depends_on:
      - control_server
    ports:
      - "8080:8080"

  clientnode:
    build: ./client_node
    container_name: client_node
    networks:
      simnet:
        ipv4_address: 10.10.1.2
    depends_on:
      - control_server
      - server_node

  routernode:
    build: ./router
    container_name: router
    networks:
      simnet:
        ipv4_address: 10.10.1.1
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - control_server

  adversarynode:
    build: ./adversary
    container_name: adversary
    networks:
      simnet:
        ipv4_address: 10.10.1.3
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - control_server

networks:
  simnet:
    ipam:
      config:
        - subnet: 10.10.0.0/16

